[General]
UseTabs=false
IndentWidth=4
NewlineType=native
NormalizeOrder=true
FunctionsSpacing=true
ObjectsSpacing=true
MaxColumnWidth=-1
SortImports=true
SemicolonRule=always

; https://doc.qt.io/qt-6/qtqml-tooling-qmlformat.html#settings-file
